version: '3' # version of docker-compose
services: # list of all services
  mongodb: # container name
    image: mongo # project image name
    ports:
      - 27017:27017 # host:container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes: # volumes mentioned here, should be defined below in volumes section
      - mongo-data:/data/db # volume-name:data-path-which-you-want-to-persist
  backend:
    image: backend:v1.0
    ports:
      - 3000:3000
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
# No need to mention network, as docker-componse will create new network for all these services
